services:
  - type: web
    name: telegram-bot
    env: python-3.10
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN_SECRET
    ports:
      - 10000
